export const DEFAULT_DROP_CATEGORIES: string[] = [
  'American',
  'Pizza',
  'Italian',
  'Mexican',
  'Tex-Mex',
  'Asian Fast Casual',
  'Chinese',
  'Japanese',
  'Thai',
  'Indian',
  'Mediterranean',
  'Burgers',
  'Sandwiches',
  'BBQ',
  'Vietnamese',
  'Korean',
  'Healthy',
  'Salads',
  'Bowls',
  'Middle Eastern',
  'Breakfast',
  'Brunch',
  'Spanish',
  'Tapas',
  'Latin American',
  'Caribbean',
  'Jamaican',
  'Peruvian',
  'Vegan / Plant-Based',
  'Merch',
  'Tickets',
  'Events'
];
